---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameoflife
spec:
  replicas: 1
  maxReplicas: 5
  minReplicas: 1
  selector:
    matchLabels:
      app: gameoflife
  template:
    metadata:
      labels:
        app: gameoflife
    spec:
      containers:
      - name: gameoflife
        image: kola225/gol:v1.1
        ports:
          - containerPort: 8080
            name: myown
            protocol: TCP
	  resources:
          requests:
            cpu: 800m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 256Mi
		volumeMounts:
		  - mountPath: /usr/local/tomcat/webapps
            name: test-volume
      volumes:
        - name: test-volume
          awsElasticBlockStore:
            volumeID: we need to provide EBS Id
            fsType: ext4
---
apiVersion: v1
kind: Service
metadata:
  name: gameoflife-svc
spec:
  selector:
    app: gameoflife
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30005
  type: NodePort
